#!/usr/bin/env python3
"""Configure the Android project generated by `flutter create` for EnglishForge.

The source repository intentionally does not commit Flutter-generated platform files.
GitHub Actions creates Android and this script applies the native requirements of
flutter_local_notifications 22.x, recording, the branded launcher icon, and API 36.
"""

from pathlib import Path
import re
import shutil

ROOT = Path(__file__).resolve().parents[1]
ANDROID = ROOT / "android"
APP_GRADLE = ANDROID / "app" / "build.gradle.kts"
SETTINGS = ANDROID / "settings.gradle.kts"
WRAPPER = ANDROID / "gradle" / "wrapper" / "gradle-wrapper.properties"
MANIFEST = ANDROID / "app" / "src" / "main" / "AndroidManifest.xml"


def require(path: Path) -> str:
    if not path.exists():
        raise SystemExit(f"Expected generated file not found: {path}")
    return path.read_text(encoding="utf-8")


def replace_required(text: str, pattern: str, replacement: str, label: str) -> str:
    updated, count = re.subn(pattern, replacement, text, flags=re.MULTILINE)
    if count == 0:
        raise SystemExit(f"Could not patch {label}; Flutter template may have changed.")
    return updated


def configure_gradle() -> None:
    app = require(APP_GRADLE)
    app = replace_required(
        app,
        r"^\s*compileSdk\s*=\s*.+$",
        "    compileSdk = 36",
        "compileSdk",
    )
    app = replace_required(
        app,
        r"^\s*minSdk\s*=\s*.+$",
        "        minSdk = 23",
        "minSdk",
    )
    app = replace_required(
        app,
        r"^\s*targetSdk\s*=\s*.+$",
        "        targetSdk = 36",
        "targetSdk",
    )
    app = re.sub(
        r"sourceCompatibility\s*=\s*JavaVersion\.VERSION_\d+",
        "sourceCompatibility = JavaVersion.VERSION_17",
        app,
    )
    app = re.sub(
        r"targetCompatibility\s*=\s*JavaVersion\.VERSION_\d+",
        "targetCompatibility = JavaVersion.VERSION_17",
        app,
    )
    app = re.sub(
        r"jvmTarget\s*=\s*JavaVersion\.VERSION_\d+\.toString\(\)",
        "jvmTarget = JavaVersion.VERSION_17.toString()",
        app,
    )
    app = re.sub(
        r"jvmTarget\s*=\s*[\"']\d+[\"']",
        'jvmTarget = "17"',
        app,
    )
    if "isCoreLibraryDesugaringEnabled" not in app:
        app = app.replace(
            "    compileOptions {",
            "    compileOptions {\n        isCoreLibraryDesugaringEnabled = true",
            1,
        )
    if "multiDexEnabled" not in app:
        app = app.replace(
            "    defaultConfig {",
            "    defaultConfig {\n        multiDexEnabled = true",
            1,
        )
    if "coreLibraryDesugaring(" not in app:
        app += """

dependencies {
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")
    implementation("androidx.window:window:1.0.0")
    implementation("androidx.window:window-java:1.0.0")
}
"""
    APP_GRADLE.write_text(app, encoding="utf-8")

    settings = require(SETTINGS)
    settings = replace_required(
        settings,
        r'id\("com\.android\.application"\)\s+version\s+"[^"]+"',
        'id("com.android.application") version "8.11.1"',
        "Android Gradle Plugin version",
    )
    SETTINGS.write_text(settings, encoding="utf-8")

    wrapper = require(WRAPPER)
    wrapper = replace_required(
        wrapper,
        r"distributionUrl=.*gradle-[^-]+-(?:all|bin)\.zip",
        "distributionUrl=https\\://services.gradle.org/distributions/gradle-8.13-all.zip",
        "Gradle wrapper version",
    )
    WRAPPER.write_text(wrapper, encoding="utf-8")


def configure_manifest() -> None:
    manifest = """<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <application
        android:label="EnglishForge"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher"
        android:allowBackup="true"
        android:fullBackupContent="true"
        android:usesCleartextTraffic="false">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:taskAffinity=""
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <receiver
            android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver"
            android:exported="false" />
        <receiver
            android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON" />
            </intent-filter>
        </receiver>

        <meta-data android:name="flutterEmbedding" android:value="2" />
    </application>

    <queries>
        <intent>
            <action android:name="android.intent.action.PROCESS_TEXT" />
            <data android:mimeType="text/plain" />
        </intent>
    </queries>
</manifest>
"""
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(manifest, encoding="utf-8")


def configure_icons() -> None:
    source_root = ROOT / "tool" / "android_resources"
    res_root = ANDROID / "app" / "src" / "main" / "res"
    for source in source_root.glob("mipmap-*/ic_launcher.png"):
        target = res_root / source.parent.name / source.name
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)


def configure_properties() -> None:
    properties = ANDROID / "gradle.properties"
    text = require(properties)
    additions = {
        "android.useAndroidX": "true",
        "android.enableJetifier": "true",
        "org.gradle.jvmargs": "-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError",
    }
    lines = text.splitlines()
    for key, value in additions.items():
        pattern = re.compile(rf"^{re.escape(key)}=")
        found = False
        for index, line in enumerate(lines):
            if pattern.match(line):
                lines[index] = f"{key}={value}"
                found = True
                break
        if not found:
            lines.append(f"{key}={value}")
    properties.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    configure_gradle()
    configure_manifest()
    configure_icons()
    configure_properties()
    print("Android project configured for EnglishForge.")


if __name__ == "__main__":
    main()
